### ISSUE TITLE
SQL injection threat

### ISSUE THREAD

**Issue by Wellner-Research** [bethropolis/suplike-social-website#32]
$query = "UPDATE `users` SET `emailusers` = '$mail',`usersFirstname` = '$fname',`usersSecondname` = '$lname', `bio`= '$bio' WHERE `users`.`idusers` = '" . $_SESSION['userId'] . "'";
    $result = $conn->query($query);
    header("Location: ../settings.php?profile&success=profchange");
  
  in settings.inc.php is EXTREMELY vulnerable to sql injections, and doesn't work with some special characters.

**Comment by Wellner-Research** [comment]
Try this code:
   ```
 $stmt = $conn->prepare(query: "UPDATE `users` SET `emailusers` = ?, `usersFirstname` = ?, `usersSecondname` = ?, `bio` = ? WHERE `users`.`idusers` = ?");
    $stmt->bind_param( "sssss",  $mail,  $fname, $lname, $bio, $_SESSION['userId']);
    $stmt->execute();
```

**Comment by bethropolis** [comment]
yeah I really should, when I made this project I was kind if new to programming, I did do a lot of updates and did move to prepared statement but I didn't cover most of the codebase

thank you, I'll reopen the project solely to fix this and add some better practices

**Comment by Wellner-Research** [comment]
thank you so much! Suplike is such an amazing project. Thanks so much for all the effort you put into this website. I really respect that you gave it MIT licence. I personally got into PHP from my interest in SQL injections and am new to this too. This site has really helped me know the language better. 

thanks so much! the amount of effort put into this website is literally insane.

**Comment by bethropolis** [comment]
you're welcome
